# Generated by Django 5.2.5 on 2025-08-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IN', 'India'), ('IE', 'Ireland'), ('IT', 'Italy'), ('JP', 'Japan'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PT', 'Portugal'), ('RU', 'Russian Federation'), ('SA', 'Saudi Arabia'), ('ZA', 'South Africa'), ('US', 'United States'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='ES', max_length=2, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Imagen de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
