# Generated by Django 4.2.23 on 2025-08-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pais',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IN', 'India'), ('IE', 'Ireland'), ('IT', 'Italy'), ('JP', 'Japan'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PT', 'Portugal'), ('RU', 'Russian Federation'), ('SA', 'Saudi Arabia'), ('ZA', 'South Africa'), ('US', 'United States'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='ES', max_length=2, null=True, verbose_name='País'),
        ),
    ]
