# Generated by Django 4.2.23 on 2026-08-26 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_medio',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valoración media'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_valoraciones',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de valoraciones'),
        ),
    ]
