# Generated by Django 5.2.5 on 2025-08-25 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='reloj_images/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
