# Generated by Django 4.2.23 on 2025-09-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0002_reloj_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reloj',
            name='stock',
        ),
    ]
