# Generated by Django 4.2.23 on 2025-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj', '0003_remove_reloj_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloj',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
