# Generated by Django 4.2.23 on 2025-09-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reloj', '0005_reloj_price_currency_alter_reloj_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reloj', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
