COUNTRIES = (
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('BR', 'Brazil'),
    ('CA', 'Canada'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CR', 'Costa Rica'),
    ('CU', 'Cuba'),
    ('DE', 'Germany'),
    ('ES', 'Spain'),
    ('FR', 'France'),
    ('GB', 'United Kingdom'),
    ('IN', 'India'),
    ('IE', 'Ireland'),
    ('IT', 'Italy'),
    ('JP', 'Japan'),
    ('MX', 'Mexico'),
    ('NG', 'Nigeria'),
    ('PK', 'Pakistan'),
    ('PE', 'Peru'),
    ('PT', 'Portugal'),
    ('RU', 'Russian Federation'),
    ('SA', 'Saudi Arabia'),
    ('ZA', 'South Africa'),
    ('US', 'United States'),
    ('UY', 'Uruguay'),
    ('VE', 'Venezuela'),
)