# Generated by Django 4.2.23 on 2025-09-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reloj', '0006_reloj_vendido_alter_reloj_user'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordendecompra')),
                ('reloj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj.reloj')),
            ],
        ),
    ]
