# Generated by Django 4.2.23 on 2025-09-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdeorden',
            name='cantidad',
        ),
    ]
