# Generated by Django 4.2.23 on 2025-09-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(choices=[('contado', 'Contado'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='contado', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
