# Generated by Django 4.2.23 on 2025-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='metodo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20),
        ),
    ]
